name: Build and Push Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t imageku .

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u julianpratamaa --password-stdin

      - name: Tag image
        run: docker tag imageku ghcr.io/julianpratamaa/imageku:latest

      - name: Push image
        run: docker push ghcr.io/julianpratamaa/imageku:latest
